apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # no need to reach from outside
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: cbagade/kub-demo-auth:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: cbagade/kub-demo-users-2:latest
        env:
        - name: AUTH_ADDRESS
          #value: "10.96.28.237"
          value: "auth-service.kube-learnings"

# same image as auth from pod_internal demo
# cd user_api
# docker build -t cbagade/kub-demo-users-2:latest .
# docker push cbagade/kub-demo-users-2:latest
# look at users-app.js
# ${process.env.AUTH_SERVICE_SERVICE_HOST} is auto generated by kubernetes , can be used along with process.env.AUTH_ADDRESS
# DNS would be service name . namespace
# kubectl config view --minify | grep namespace:

# kubectl apply -f app_deployment.yaml
# kubectl exec -it <user_pod> -- /bin/bash
# look at env variables  and notice AUTH_SERVICE_SERVICE_HOST

# kubectl logs <pod> -f --> for both auth and users pod
# http://localhost:30004/signup -> {     "email":"cbagade@yahoo.com",     "password":"devops" }
# http://localhost:30004/login -> {     "email":"cbagade@yahoo.com",     "password":"devops" }
# kubectl delete -f app_deployment.yaml
