apiVersion: v1
kind: Service
metadata:
  name: middleware
spec:
  selector:
    app: middleware
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
    nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: cbagade/middleware:v8
        env:
        - name: MONGO_ADDRESS
          value: "mongodb.kube-learnings" # mongo db service + . + namespace
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongouser
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongopassword
  selector:
    matchLabels:
      app: middleware


# docker build -t cbagade/middleware:v8 .
# docker push cbagade/middleware:v8
# kubectl apply -f mongo_deployment.yaml -f app_deployment.yaml
# kubectl get pods -w  (wait for pods to be in running state)
# GET app_2 /api/v1/fruits change port to 30007
# POST  app_2/api/v1/fruits change port to 30007
# Verify the changes
# GET  app_2/api/v1/fruits change port to 30007

# kubectl delete -f mongo_deployment.yaml -f app_deployment.yaml
# kubectl apply -f mongo_deployment.yaml -f app_deployment.yaml
# GET app_2/api/v1/fruits change port to 30007
# changes persisted