apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # no need to reach from outside
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: cbagade/kub-demo-auth:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: cbagade/kub-demo-users-3:latest
        env:
        - name: AUTH_ADDRESS
          #value: "10.96.28.237"
          value: "auth-service.kube-learnings"
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: credsecret
              key: email
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credsecret
              key: password


# create secret (definition above)
# echo -n 'cbagade@yahoo.com' | base64  (incorporate this value in secret)
# echo -n 'devops' | base64 (incorporate this value in secret)
# not changes in user_app.js, to pick email and password from env var

# same image as auth from pod_internal demo
# cd user_api
# docker build -t cbagade/kub-demo-users-3:latest .
# docker push cbagade/kub-demo-users-3:latest

# kubectl apply -f app_secret.yaml
# kubectl apply -f app_deployment.yaml

# kubectl logs <pod> -f --> for both auth and users pod
# http://localhost:30005/signup -> No need for body as we taking from secret
# http://localhost:30005/login -> No need for body as we taking from secret
